# Generated by Django 6.0.2 on 2026-03-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OFFICE_SUPPLY', 'Office Supply Inventory'), ('JANITORIAL', 'Janitorial Inventory')], max_length=30),
        ),
    ]
