# Generated by Django 6.0.3 on 2026-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OFFICE_SUPPLY', 'Office Supply Inventory'), ('JANITORIAL', 'Janitorial Inventory'), ('EQUIPMENT', 'Equipment Inventory')], max_length=30),
        ),
    ]
