# Generated by Django 6.0.3 on 2026-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition_status',
            field=models.CharField(blank=True, choices=[('GOOD', 'In Good Condition'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='life_span',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='inventory_custodian_slip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='life_span',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='material_requisition',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='property_return_slip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='return_condition_status',
            field=models.CharField(blank=True, choices=[('GOOD', 'In Good Condition'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('BROUGHT_BACK', 'Brought Back')], max_length=20),
        ),
    ]
