# Generated by Django 6.0.3 on 2026-03-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_item_condition_status_item_life_span_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory_custodian_slip',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='material_receipt',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
